In [6]:
import pandas as pd

In [7]:
# import dataset 
df = pd.read_csv(r'C:\DriveD\fyp\datasets\illness_dataset.csv')

In [8]:
df.loc[df['Disease'] == 'No illness'] = 0

In [9]:
df['Disease'] = df['Disease'].replace(0, 'No illness')

In [10]:
df.head()

,Disease,muscle_tension,low_energy,sleep_disturbances,changes_in_weight,difficulty_concentrating,feeling_of_worthless,low_mood,irritability,thoughts_of_death,...,inability_to_recall_important_personal_information,memory_loss_typically_related_to_trauma,sudden_onset_of_amnesia,gaps_in_memory_for_long_periods_of_time,wandering,loss_of_identity,emotional_numbness,trouble_remembering_daily_tasks,anxiety_related_to_memory_loss,confusion
0,Borderline Personality Disorder,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Eating Disorder,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Major Depressive Disorder,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,Substance Use Disorder,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ADHD (Attention Deficit Hyperactivity Disorder),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df.isnull().sum()

Disease                            0
muscle_tension                     0
low_energy                         0
sleep_disturbances                 0
changes_in_weight                  0
                                  ..
loss_of_identity                   0
emotional_numbness                 0
trouble_remembering_daily_tasks    0
anxiety_related_to_memory_loss     0
confusion                          0
Length: 186, dtype: int64

In [12]:
df['Disease'].nunique()

22

In [13]:
df["Disease"].unique()

array(['Borderline Personality Disorder', 'Eating Disorder',
       'Major Depressive Disorder', 'Substance Use Disorder',
       'ADHD (Attention Deficit Hyperactivity Disorder)',
       'Post-Traumatic Stress Disorder (PTSD)', 'Dissociative Amnesia',
       'Social Anxiety Disorder', 'Panic Disorder', 'Schizophrenia',
       'Separation Anxiety Disorder', 'Depression',
       'Generalized Anxiety Disorder (GAD)', 'Autism Spectrum Disorder',
       'Anxiety', 'No illness', 'Insomnia',
       'Dissociative Identity Disorder', 'Persistent Depressive Disorder',
       'Bipolar Disorder', 'Obsessive-Compulsive Disorder (OCD)',
       'Adjustment Disorder'], dtype=object)

In [14]:
df.shape

(8304, 186)

In [15]:
df['Disease'].value_counts()

Disease
Separation Anxiety Disorder                        391
Dissociative Amnesia                               391
Insomnia                                           390
Major Depressive Disorder                          389
Bipolar Disorder                                   389
Autism Spectrum Disorder                           388
Obsessive-Compulsive Disorder (OCD)                388
Borderline Personality Disorder                    387
ADHD (Attention Deficit Hyperactivity Disorder)    387
Schizophrenia                                      386
Substance Use Disorder                             386
Panic Disorder                                     386
Dissociative Identity Disorder                     385
Social Anxiety Disorder                            385
Eating Disorder                                    385
Persistent Depressive Disorder                     384
Generalized Anxiety Disorder (GAD)                 383
Depression                                         382
Anxiety                                            382
Post-Traumatic Stress Disorder (PTSD)              382
Adjustment Disorder                                378
No illness                                         200
Name: count, dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8304 entries, 0 to 8303
Columns: 186 entries, Disease to confusion
dtypes: int64(185), object(1)
memory usage: 11.8+ MB

In [17]:
df.describe()

,muscle_tension,low_energy,sleep_disturbances,changes_in_weight,difficulty_concentrating,feeling_of_worthless,low_mood,irritability,thoughts_of_death,physical_aches_and_pains,...,inability_to_recall_important_personal_information,memory_loss_typically_related_to_trauma,sudden_onset_of_amnesia,gaps_in_memory_for_long_periods_of_time,wandering,loss_of_identity,emotional_numbness,trouble_remembering_daily_tasks,anxiety_related_to_memory_loss,confusion
count,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,...,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000
mean,0.072977,0.038174,0.159803,0.039258,0.130539,0.070087,0.040944,0.131985,0.039740,0.044316,...,0.045279,0.044316,0.042871,0.041667,0.041787,0.039860,0.036488,0.034321,0.031190,0.031069
std,0.260114,0.191629,0.366445,0.194220,0.336916,0.255308,0.198173,0.338494,0.195359,0.205809,...,0.207929,0.205809,0.202578,0.199838,0.200114,0.195643,0.187513,0.182063,0.173841,0.173516
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000