In [39]:
import pandas as pd

In [40]:
# import dataset 
df = pd.read_csv(r'C:\DriveD\fyp\datasets\illness_dataset.csv')

In [41]:
df.head()

,Disease,muscle_tension,low_energy,sleep_disturbances,changes_in_weight,difficulty_concentrating,feeling_of_worthless,low_mood,irritability,thoughts_of_death,...,inability_to_recall_important_personal_information,memory_loss_typically_related_to_trauma,sudden_onset_of_amnesia,gaps_in_memory_for_long_periods_of_time,wandering,loss_of_identity,emotional_numbness,trouble_remembering_daily_tasks,anxiety_related_to_memory_loss,confusion
0,Borderline Personality Disorder,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Eating Disorder,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Major Depressive Disorder,0,0,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,Substance Use Disorder,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ADHD (Attention Deficit Hyperactivity Disorder),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
df.isnull().sum()

Disease                            0
muscle_tension                     0
low_energy                         0
sleep_disturbances                 0
changes_in_weight                  0
                                  ..
loss_of_identity                   0
emotional_numbness                 0
trouble_remembering_daily_tasks    0
anxiety_related_to_memory_loss     0
confusion                          0
Length: 186, dtype: int64

In [43]:
df['Disease'].nunique()

22

In [44]:
df["Disease"].unique()

array(['Borderline Personality Disorder', 'Eating Disorder',
       'Major Depressive Disorder', 'Substance Use Disorder',
       'ADHD (Attention Deficit Hyperactivity Disorder)',
       'Post-Traumatic Stress Disorder (PTSD)', 'Dissociative Amnesia',
       'Social Anxiety Disorder', 'Panic Disorder', 'Schizophrenia',
       'Separation Anxiety Disorder', 'Depression',
       'Generalized Anxiety Disorder (GAD)', 'Autism Spectrum Disorder',
       'Anxiety', 'No illness', 'Insomnia',
       'Dissociative Identity Disorder', 'Persistent Depressive Disorder',
       'Bipolar Disorder', 'Obsessive-Compulsive Disorder (OCD)',
       'Adjustment Disorder'], dtype=object)

In [45]:
df.shape

(8304, 186)

In [46]:
df['Disease'].value_counts()

Disease
Obsessive-Compulsive Disorder (OCD)                388
Persistent Depressive Disorder                     387
Autism Spectrum Disorder                           387
Borderline Personality Disorder                    386
Separation Anxiety Disorder                        386
Bipolar Disorder                                   386
Dissociative Identity Disorder                     386
Insomnia                                           386
Anxiety                                            386
Eating Disorder                                    386
Adjustment Disorder                                386
Schizophrenia                                      386
Panic Disorder                                     386
Social Anxiety Disorder                            386
Dissociative Amnesia                               386
ADHD (Attention Deficit Hyperactivity Disorder)    386
Substance Use Disorder                             386
Major Depressive Disorder                          386
Generalized Anxiety Disorder (GAD)                 385
Post-Traumatic Stress Disorder (PTSD)              385
Depression                                         381
No illness                                         201
Name: count, dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8304 entries, 0 to 8303
Columns: 186 entries, Disease to confusion
dtypes: int64(185), object(1)
memory usage: 11.8+ MB

In [48]:
df.describe()

,muscle_tension,low_energy,sleep_disturbances,changes_in_weight,difficulty_concentrating,feeling_of_worthless,low_mood,irritability,thoughts_of_death,physical_aches_and_pains,...,inability_to_recall_important_personal_information,memory_loss_typically_related_to_trauma,sudden_onset_of_amnesia,gaps_in_memory_for_long_periods_of_time,wandering,loss_of_identity,emotional_numbness,trouble_remembering_daily_tasks,anxiety_related_to_memory_loss,confusion
count,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,...,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000,8304.000000
mean,0.073459,0.038536,0.159321,0.037813,0.130419,0.068762,0.038174,0.130178,0.036850,0.040824,...,0.032876,0.032274,0.032274,0.032996,0.032514,0.032033,0.031431,0.031310,0.031069,0.030829
std,0.260903,0.192497,0.365997,0.190755,0.336784,0.253064,0.191629,0.336520,0.188404,0.197894,...,0.178322,0.176736,0.176736,0.178637,0.177373,0.176098,0.174489,0.174165,0.173516,0.172863
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000